In [4]:
import numpy as np

a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
lst = [1,2,3] # This is 1D list
print(lst)

[1, 2, 3]


In [6]:
lst2 = [[1,2,3],[4,5,6],[7,8,9]] # This is 2D list
print(lst2)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [7]:
type(lst2)

list

In [10]:
arr = np.array(lst2) # This is 2D array
print(arr)
print(type(arr))
print(arr.shape)
print(arr.dtype)
print(arr.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(3, 3)
int32
2


# RANDOM LIBRARY

In [47]:
arr1 = np.random.random((3,3,3)) # This will create 3x3 array with random values
print(arr1)

[[[0.99384809 0.31625913 0.78730351]
  [0.90731084 0.10858748 0.39260359]
  [0.43345258 0.73287807 0.39380109]]

 [[0.12574535 0.0322612  0.2129504 ]
  [0.18589159 0.57081552 0.97790383]
  [0.99701248 0.53334254 0.98300601]]

 [[0.74914102 0.47133173 0.87054072]
  [0.80390778 0.83144919 0.35511759]
  [0.82646411 0.90078991 0.59370859]]]


In [15]:
arr2 = np.random.randint(0,11,(3,3)) #This will generate random integer between 0 to 10
print(arr2)

[[10  5  2]
 [ 8  0  9]
 [ 6  1  3]]


In [17]:
arr3 = np.random.randn(3,3) # This is standard normal distribution
print(arr3)

[[-1.69208684 -0.11745763  0.46373905]
 [-0.78557212 -2.86821397  1.88645944]
 [-0.13450397  1.30607333 -1.51726138]]


In [18]:
arr4 = np.random.normal(0,1,(3,3)) # This is normal distribution
print(arr4)

[[ 0.14933855  0.06987771  1.21909535]
 [-1.32646081 -0.61928909 -2.29696443]
 [-0.36795987 -0.17015872  0.25721452]]


In [19]:
arr5 = np.random.uniform(0,1,(3,3)) # This is uniform distribution
print(arr5)

[[0.78191385 0.9953903  0.12185675]
 [0.6478543  0.77683399 0.90602389]
 [0.52551454 0.24382471 0.44810681]]


In [20]:
arr6 = np.random.choice([1,2,3,4,5,6,7,8,9],(3,3)) # This will generate random number from the list
print(arr6)

[[7 1 1]
 [5 5 7]
 [4 7 4]]


In [21]:
arr7 = np.random.permutation([1,2,3,4,5,6,7,8,9]) # This will generate random permutation from the list
print(arr7)

[9 8 7 2 1 4 5 6 3]


# SEQUENCE

In [29]:
arr8 = np.arange(0,12) # This will generate array sequence from 0 to 10
print(arr8)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [26]:
arr9 = np.linspace(0,10,9) # This will generate array sequence from 0 to 10 with 5 elements and equidistant
print(arr9)

[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]


In [28]:
arr10 = np.eye(3) # This will generate identity matrix
print(arr10)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [41]:
arr11 = np.random.random((3,4)) # This will generate 3x4 array with random values
arr11 = np.reshape(arr11 , (2,6)) # This will reshape the array
print(arr11)

[[0.69903083 0.95120737 0.23052874 0.44402576 0.42461883 0.4205114 ]
 [0.83361632 0.87855791 0.25379399 0.46197253 0.50877828 0.21548489]]


In [44]:
print(arr11) #this is a 2D array
arr11 = arr11.flatten() # This will flatten the array
print('-'*20)
print(arr11) # This is a 1D array

[0.69903083 0.95120737 0.23052874 0.44402576 0.42461883 0.4205114
 0.83361632 0.87855791 0.25379399 0.46197253 0.50877828 0.21548489]
--------------------
[0.69903083 0.95120737 0.23052874 0.44402576 0.42461883 0.4205114
 0.83361632 0.87855791 0.25379399 0.46197253 0.50877828 0.21548489]


In [46]:
arr12 = np.arange(20).reshape(5,4) # This will generate 5x4 array
print(arr12)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


# Arithematics Operations

In [50]:
ar = np.array([1,2,3,4,5,6,7,8,9,10]) # 1D array
print(ar)

ar = ar+1
ar1 = ar-2
ar2 = ar*2

print(ar)
print(ar1)
print(ar2)


[ 1  2  3  4  5  6  7  8  9 10]
[ 2  3  4  5  6  7  8  9 10 11]
[0 1 2 3 4 5 6 7 8 9]
[ 4  6  8 10 12 14 16 18 20 22]


In [60]:
print(arr) # This is 2D array
print('-'*20)
print(arr.sum())
print(arr.sum(axis=0)) # This will sum the column
print(arr.sum(axis=1)) # This will sum the row
print('-'*20)
print(arr.max(axis=1))
print(arr.max(axis=0))
print('-'*20)
print(arr.min(axis=1))
print(arr.min(axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------
45
[12 15 18]
[ 6 15 24]
--------------------
[3 6 9]
[7 8 9]
--------------------
[1 4 7]
[1 2 3]


In [79]:
Z = np.arange(4, 13).reshape(3,3)
Z

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [80]:
print(arr + Z) # Addition of two array

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

In [81]:
X = np.arange(1,13).reshape(3,4)
print(X)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [83]:
print(X+Z) # This will give error because of shape mismatch

In [84]:
arr.dot(Z)

array([[ 48,  54,  60],
       [111, 126, 141],
       [174, 198, 222]])

In [89]:
trans = arr.T # This will transpose the array matrix
print(arr)
print('-'*20)
print(trans)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------
[[1 4 7]
 [2 5 8]
 [3 6 9]]


# Indexing

In [92]:
lst = [1,2,3,4,5,6,7,8,9,10]
print(lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [93]:
lst[::-1] # This will reverse the list

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [94]:
lst[::2] # This will print alternate element from the list

[1, 3, 5, 7, 9]

In [96]:
lst[1::2] # first part is starting index and second part is ending index ...here means ending and then last part is step size

[2, 4, 6, 8, 10]

# Sorting


In [111]:
a = np.array([[4,7,1,5] , [0,8,9,1] , [11,78,112,34] , [9,90,76,2]])
print(a)
a.T
# np.sort(a, axis=0 , kind='quicksort') # This will sort the array column wise
np.sort(a, axis=1 , kind='mergesort')   # This will sort the array row wise

[[  4   7   1   5]
 [  0   8   9   1]
 [ 11  78 112  34]
 [  9  90  76   2]]


array([[  1,   4,   5,   7],
       [  0,   1,   8,   9],
       [ 11,  34,  78, 112],
       [  2,   9,  76,  90]])

In [120]:
ar[3]=9
ar[5]=1
ar[0]=10
ar[7]=2
print(ar)
ar.sort() # makes the original array sorted
s = sorted(ar) # This will not change the original array
print(s)
print(ar)

[10  2  2  9  6  1  9  2 10 11]
[1, 2, 2, 2, 6, 9, 9, 10, 10, 11]
[ 1  2  2  2  6  9  9 10 10 11]


# Merging

In [127]:
fd = np.array([[1,2,3] ,[4,5,6]])
fd1 = np.array([[7,8,9] ,[10,11,12]])

In [128]:
np.hstack((fd,fd1)) # This will concatenate the array horizontally

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [129]:
np.vstack((fd,fd1)) # This will concatenate the array vertically

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [137]:
ar = np.concatenate((fd,fd1) , axis=0) # This will concatenate the array vertically
df = np.array([4,5,9,10]).reshape(4,1)
ar = np.hstack((ar,df))
# print(df)
print(ar)

[[ 1  2  3  4]
 [ 4  5  6  5]
 [ 7  8  9  9]
 [10 11 12 10]]


In [131]:
np.concatenate((fd,fd1) , axis=1) # This will concatenate the array horizontally

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [138]:
np.hsplit(ar,2) # This will split the array horizontally


[array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]]),
 array([[ 3,  4],
        [ 6,  5],
        [ 9,  9],
        [12, 10]])]

In [139]:
np.vsplit(ar,2) # This will split the array vertically

[array([[1, 2, 3, 4],
        [4, 5, 6, 5]]),
 array([[ 7,  8,  9,  9],
        [10, 11, 12, 10]])]

# Arrays Slicing

In [142]:
print(ar)

[[ 1  2  3  4]
 [ 4  5  6  5]
 [ 7  8  9  9]
 [10 11 12 10]]


In [143]:
ar[:,:] # , is used to separate between rows and columns

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  5],
       [ 7,  8,  9,  9],
       [10, 11, 12, 10]])

In [151]:
ar[2:,-2:]

array([[ 9,  9],
       [12, 10]])

In [ ]:
# Code to convert to HTML
# jupyter nbconvert --to html Data\ Science/Data\ Analytics/Numpy/file.ipynb


# Automation